### ISSUE TITLE
LiteDOS in dir2atr

### ISSUE THREAD

**Issue by ojaksch** [HiassofT/AtariSIO#2]
What about implementing [LiteDOS](http://www.mr-atari.com/Mr.Atari/LiteDOS/) into dir2atr?
I've managed to extract it's bootsector(s) and to implant them by using dir2atr's -b parameter. The created image boots showing LiteDOS's message but machine crashes afterwards.

**Comment by HiassofT** [comment]
Quite tricky, as LiteDOS isn't really DOS2.x compatible. It doesn't use a standard DOS.SYS file but stores the DOS data directly in sectors 4-16 (4-10 on DD disks). Also it seems to use lowercase letters for it's "LiteDUP.SYS" filename. The most important issue though is that the sector allocation scheme is completely different to DOS2.x/MyDOS so compatibility to DOS2.x is limited to read-only.

I had a quick go at hacking support for "extended boot data sectors" into dir2atr and pushed an experimental test branch here: https://github.com/HiassofT/AtariSIO/tree/extended-bootsectors - with the 1920 boot data bytes extracted from the LiteDOS 3.06 atr I could create a bootable ATR but it's usability is quite limited (as writing won't work). So I'm not sure if I'll include that change in the master branch, but feel free to do some tests with it.

**Comment by ojaksch** [comment]
Thanks for the hack, Hias. I agree that this is somewhat useless w/o wrote support, apart for demo disks for example - but I could use your MyPicoDos autorun mode instead then ;)
I've found an elderly github repo for [LiteDOS](https://github.com/mr-atari/LiteDOS) but I'll ask him if he's interested in collaboration and opening his sources, at least for his disk format routine(s).

**Comment by mr-atari** [comment]
Hi All,

Nice to have a look at this. As we speak SDX is adding a read_only feature for LiteDOS.

Picture, standard 720 sector LiteDOS disk:
![LiteDOS 4 clusters 720 sector disk](https://user-images.githubusercontent.com/43779353/99497848-c7ce5500-2976-11eb-81ac-5ec5186e96f4.png)

LiteDOS is very simple to read. It's basically a DOS 2.x file-format but uses clusters for saving and directory-size.
There is a hidden feature for subdirectories, currently locked due to bugs. Same byte/bit in the file-status.
Dos-id is negative, last 7 bit, the clustersize-1.

Disks larger then 1024 sectors have no file-check in the sector links.
Also same byte/bit in the file-status.

Grtz,
Sijmen.

**Comment by mr-atari** [comment]
About bootsectors:
Sectors 1-15 are reserved as "bootsectors" on SD-disks / SD-partitons.
Sectors 1-10 are reserved as "bootsectors" on DD-disks / DD-partitons.
Sectors 1-3 + 1026-1039 are reserved as "bootsectors" MD-disks.

To be precise, LiteDOS has 1 bootsector.
It detects density and then continues on the appropriate sector.
Used sectors for LiteDOS core are removed from the VTOC bit-table.
